### ISSUE TITLE
误封 Missealing

### ISSUE THREAD

**Issue by ayami19** [sti-233/Bilix-PreBuilds#5]

**Comment by SamZhou-2019** [comment]
> 我没有用bilix发布评论 今天突然被封了 请求解封 UID:608340678
> 
> I never use bilix Post a comment Suddenly banned today Request unsealing UID:608340678 ![图片20241031145235](https://private-user-images.githubusercontent.com/177840705/381854273-8a63a44f-0dd9-4b98-8edb-e6846f932ed7.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzAzNjE1MDAsIm5iZiI6MTczMDM2MTIwMCwicGF0aCI6Ii8xNzc4NDA3MDUvMzgxODU0MjczLThhNjNhNDRmLTBkZDktNGI5OC04ZWRiLWU2ODQ2ZjkzMmVkNy5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDMxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAzMVQwNzUzMjBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xMjhkNTI5YTg5YjQyNGY1NGIxODcwODJlNzRhY2ZkYmQ1NmVlYzVjMTBiZWEzN2M5NmI3NjQyZjFkNTZlYjkxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.JohYh1SoeXzeCaGVYpeTPT3nt-z_3QTaVT5q03ciegA)

这不是误封，原作者可能弃坑了，原仓库也封包（archived）了。不知道出什么事了。
![Screenshot_20241031_155556](https://github.com/user-attachments/assets/f06565a1-84f1-4155-ac78-448a06e6afdf)

**Comment by ala-404** [comment]
有人在b站大规模宣传，并且跟官方爆了，现在全面停用> > 我没有用bilix发布评论 今天突然被封了 请求解封 UID:608340678
> > 
> > I never use bilix Post a comment Suddenly banned today Request unsealing UID:608340678 ![图片20241031145235](https://private-user-images.githubusercontent.com/177840705/381854273-8a63a44f-0dd9-4b98-8edb-e6846f932ed7.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzAzNjE1MDAsIm5iZiI6MTczMDM2MTIwMCwicGF0aCI6Ii8xNzc4NDA3MDUvMzgxODU0MjczLThhNjNhNDRmLTBkZDktNGI5OC04ZWRiLWU2ODQ2ZjkzMmVkNy5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDMxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAzMVQwNzUzMjBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xMjhkNTI5YTg5YjQyNGY1NGIxODcwODJlNzRhY2ZkYmQ1NmVlYzVjMTBiZWEzN2M5NmI3NjQyZjFkNTZlYjkxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.JohYh1SoeXzeCaGVYpeTPT3nt-z_3QTaVT5q03ciegA)
> 
> 这不是误封，原作者可能弃坑了，原仓库也封包（archived）了。不知道出什么事了。
> 
> （不知道带原仓库的链接或者图片算不算宣传，就删掉了，你可以在网上搜索一下原仓库）
>

**Comment by SamZhou-2019** [comment]
> 有人在b站大规模宣传，并且跟官方爆了，现在全面停用> > 我没有用bilix发布评论 今天突然被封了 请求解封 UID:608340678
> 
> > > I never use bilix Post a comment Suddenly banned today Request unsealing UID:608340678 ![图片20241031145235](https://private-user-images.githubusercontent.com/177840705/381854273-8a63a44f-0dd9-4b98-8edb-e6846f932ed7.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzAzNjE1MDAsIm5iZiI6MTczMDM2MTIwMCwicGF0aCI6Ii8xNzc4NDA3MDUvMzgxODU0MjczLThhNjNhNDRmLTBkZDktNGI5OC04ZWRiLWU2ODQ2ZjkzMmVkNy5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDMxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAzMVQwNzUzMjBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xMjhkNTI5YTg5YjQyNGY1NGIxODcwODJlNzRhY2ZkYmQ1NmVlYzVjMTBiZWEzN2M5NmI3NjQyZjFkNTZlYjkxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.JohYh1SoeXzeCaGVYpeTPT3nt-z_3QTaVT5q03ciegA)
> > 
> > 
> > 这不是误封，原作者可能弃坑了，原仓库也封包（archived）了。不知道出什么事了。
> > （不知道带原仓库的链接或者图片算不算宣传，就删掉了，你可以在网上搜索一下原仓库）

啊，这么离谱
